---
    # Auto-Update for RedHat and Debian variants
    - name: Install yum-cron
      yum: name=yum-cron
           update_cache=yes
           state=latest
      when: ansible_os_family == "RedHat"

    - name: Enable and start yum-cron
      systemd: name=yum-cron
               enabled=yes
               state=started
      when: ansible_os_family == "RedHat"

    - name: Configure autoupdates for Redhat variants
      lineinfile: dest=/etc/yum/yum-cron.conf
                  regex='^apply_updates ='
                  line='apply_updates = no'
                  state=present
      when: ansible_os_family == "RedHat"

    - name: Configure autoupdates for Debian variants
      apt: name=unattended-upgrades
           update_cache=yes
           state=latest
      when: ansible_os_family == "Debian"

    - name: Copy upgrades configuration files.
      template: src="../templates/{{ item }}.j2"
                dest="/etc/apt/apt.conf.d/{{ item }}"
                owner: root
                group: root
                mode: 0644
      with_items:
        - 10periodic
        - 50unattended-upgrades
      when: ansible_os_family == "Debian"
