---
- hosts: boxprepper
  remote_user: zuser0
  become: yes
  become_method: sudo

  vars:
    centos_hostname: 'new.centos.box'
    debian_hostname: 'new.debian.box'

  tasks:
    # Check if 'systemd' is installed on the OS, if not, install it.
    - name: Check or Install 'systemd' on RedHat variants
      yum: name=systemd
           update_cache=yes
           state=latest
      when: ansible_os_family == "RedHat"

    - name: Check or Install 'systemd' on Debian variants
      apt: name=systemd
           update_cache=yes
           state=latest
      when: ansible_os_family == "Debian"

    - name: Set the hostname for 'RedHat' variants
      action: shell hostnamectl set-hostname {{ centos_hostname }}
      when: ansible_os_family == "RedHat"

    - name: Set the hostname for 'Debian' variants
      action: shell hostnamectl set-hostname {{ debian_hostname }}
      when: ansible_os_family == "Debian"
