---
    - name: Install fail2ban in Debian/Ubuntu
      apt: name=fail2ban
           update_cache=yes
           state=latest
      when: ansible_os_family == "Debian"

    - name: Install epel and fail2ban in CentOS/Redhat
      yum: name={{ item }}
           update_cache=yes
           state=latest
      when: ansible_os_family == "Redhat"
      with_items:
        - epel-release
        - fail2ban
